name: Deploy Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: ".,! .git"
          target: "/tmp/website"

      - name: Copy files to Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/website/. /var/www/html/
            sudo rm -rf /var/www/html/.git
            sudo systemctl reload nginx
